export const environment = {
  production: false,
 // apiUrl: "https://localhost:44370/api",
 //apiUrl: "https://rdw.cortracker360.com/api",
 apiUrl: "https://interior.cortracker360.com/api",
  //apiUrl: "https://machinery.cortracker360.com/api",
 //baseurl: "https://localhost:44370",
  //baseurl: "https://machinery.cortracker360.com",
  //baseurl: "https://rdw.cortracker360.com",
 baseurl: "https://interior.cortracker360.com",
  //baseurl: "https://localhost:44370",
  resumePath: 'Uploads/Resumes/',
  companyNewsUrl : 'https://interior.cortracker360.com/api/CompanyNews',
  //companyNewsUrl : 'https://rdw.cortracker360.com/api/CompanyNews',
  // ddcopies : 'https://rdw.cortracker360.com/DDCopies/',
  ddcopies : 'https://interior.cortracker360.com/DDCopies/',
  //companyNewsUrl : 'https://localhost:44370/api/CompanyNews',
  isDebugMode: true,
  LettersPath: 'Uploads/EmployeeLetters/',
  leaveDocumentPath: '/uploads/LeaveDocuments/',
  documentsPath: 'Uploads/CandidateDocuments/',
  fileBaseUrl: "https://interior.cortracker360.com/",
  //fileBaseUrl: "https://rdw.cortracker360.com/",
};